name=RetroJoystick
version=1.0.0
author=Jon Thysell <thysell@gmail.com>, John Milner, Bill Porter, Wolfgang
maintainer=Wolfgang
sentence=A library to allow using old console joysticks to game on PC
paragraph=This project provides code so you can bring back to life your old controller with native plug-and-play support for Linux and Windows that can read USB HID class.
category=Device Controlc
url=https://github.com/Wolf359Stella/RetroJoystick
architectures=avr
